/* The glyph behind every icon. Logos come from Simple Icons (CC0, 24 unit square) and original
   drawings fill the gaps. Every colour is an icon role, never the brand's own colour, so the
   explorer reads as one theme. The keys become SVG filenames. */

import {
  siAngular,
  siAstro,
  siBiome,
  siBun,
  siC,
  siCplusplus,
  siCss,
  siDart,
  siDeno,
  siDjango,
  siDocker,
  siDotenv,
  siDotnet,
  siElixir,
  siEslint,
  siGit,
  siGithub,
  siGithubactions,
  siGnubash,
  siGo,
  siGraphql,
  siHaskell,
  siHtml5,
  siJavascript,
  siJest,
  siJson,
  siJupyter,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLess,
  siLua,
  siMarkdown,
  siMongodb,
  siMysql,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNpm,
  siPhp,
  siPnpm,
  siPostgresql,
  siPrettier,
  siPrisma,
  siPython,
  siR,
  siReact,
  siRedis,
  siRuby,
  siRubyonrails,
  siRust,
  siSass,
  siScala,
  siSpring,
  siSqlite,
  siStorybook,
  siSvelte,
  siSvg,
  siSwift,
  siTailwindcss,
  siTerraform,
  siToml,
  siTypescript,
  siVite,
  siVitest,
  siVuedotjs,
  siWebpack,
  siXml,
  siYaml,
  siYarn,
  siZig,
} from "simple-icons";
import type { Hex } from "../color.ts";
import { icon } from "../roles.ts";
import type { Layer } from "./badge.ts";
import { generic } from "./generic.ts";

function logo({ path }: { path: string }, fill: Hex, split?: Hex): readonly Layer[] {
  return [split === undefined ? { d: path, fill } : { d: path, fill, split }];
}

// Line-drawn logos fade under the sticker outline, so they are drawn without one.
function lineLogo({ path }: { path: string }, fill: Hex): readonly Layer[] {
  return [{ d: path, fill, noOutline: true }];
}

export const glyphs = {
  python: logo(siPython, icon.sky, icon.gold),
  typescript: logo(siTypescript, icon.sky),
  javascript: logo(siJavascript, icon.lemon),
  rust: logo(siRust, icon.amber),
  go: logo(siGo, icon.cyan),
  php: logo(siPhp, icon.violet),
  ruby: logo(siRuby, icon.red),
  kotlin: logo(siKotlin, icon.violet, icon.magenta),
  swift: logo(siSwift, icon.amber),
  dart: logo(siDart, icon.teal),
  c: logo(siC, icon.sky),
  cpp: logo(siCplusplus, icon.sky),
  lua: logo(siLua, icon.violet),
  r: logo(siR, icon.sky),
  scala: logo(siScala, icon.red),
  elixir: logo(siElixir, icon.violet),
  haskell: logo(siHaskell, icon.violet),
  zig: logo(siZig, icon.amber),
  dotnet: lineLogo(siDotnet, icon.silver),
  csharp: generic.csharp,
  java: generic.java,
  powershell: generic.powershell,
  shell: logo(siGnubash, icon.lime),

  html: logo(siHtml5, icon.amber),
  css: logo(siCss, icon.violet),
  sass: logo(siSass, icon.magenta),
  less: logo(siLess, icon.sky),
  react: logo(siReact, icon.cyan),
  vue: logo(siVuedotjs, icon.lime),
  svelte: logo(siSvelte, icon.red),
  angular: logo(siAngular, icon.red),
  nextjs: logo(siNextdotjs, icon.silver),
  astro: logo(siAstro, icon.magenta),
  tailwind: logo(siTailwindcss, icon.cyan),
  django: logo(siDjango, icon.lime),
  laravel: lineLogo(siLaravel, icon.red),
  rails: logo(siRubyonrails, icon.red),
  spring: logo(siSpring, icon.lime),

  nodejs: logo(siNodedotjs, icon.lime),
  deno: logo(siDeno, icon.silver),
  bun: logo(siBun, icon.gold),
  npm: logo(siNpm, icon.red),
  pnpm: logo(siPnpm, icon.gold),
  yarn: logo(siYarn, icon.sky),
  vite: logo(siVite, icon.violet, icon.lemon),
  webpack: logo(siWebpack, icon.sky),
  eslint: logo(siEslint, icon.violet),
  prettier: logo(siPrettier, icon.pink),
  biome: logo(siBiome, icon.sky),
  vitest: logo(siVitest, icon.lime, icon.lemon),
  jest: logo(siJest, icon.red),
  storybook: logo(siStorybook, icon.magenta),
  docker: logo(siDocker, icon.sky),
  kubernetes: logo(siKubernetes, icon.sky),
  terraform: logo(siTerraform, icon.violet),
  nginx: logo(siNginx, icon.lime),

  json: logo(siJson, icon.gold),
  yaml: logo(siYaml, icon.red),
  toml: logo(siToml, icon.amber),
  xml: lineLogo(siXml, icon.amber),
  markdown: logo(siMarkdown, icon.silver),
  graphql: logo(siGraphql, icon.magenta),
  prisma: logo(siPrisma, icon.teal),
  sqlite: logo(siSqlite, icon.sky),
  postgresql: lineLogo(siPostgresql, icon.mist),
  mysql: lineLogo(siMysql, icon.mist),
  mongodb: logo(siMongodb, icon.lime),
  redis: logo(siRedis, icon.red),
  jupyter: logo(siJupyter, icon.amber),
  env: logo(siDotenv, icon.lemon),
  svg: logo(siSvg, icon.amber),

  git: logo(siGit, icon.magenta),
  github: logo(siGithub, icon.silver),
  "github-actions": logo(siGithubactions, icon.sky),

  license: generic.license,
  image: generic.image,
  lock: generic.lock,
  test: generic.test,
  config: generic.config,
  file: generic.file,
  folder: generic.folder,
  "folder-open": generic["folder-open"],
} as const satisfies Record<string, readonly Layer[]>;

export type IconName = keyof typeof glyphs;
