/* The Vanessë file icon theme. Maps file extensions, file names and folder names to icons, and
   names the icons for plain files and folders. VS Code prefers a file name match over an
   extension match. Keys are listed at
   https://code.visualstudio.com/api/extension-guides/file-icon-theme */

import { glyphs, type IconName } from "./glyphs.ts";

type IconMap = Record<string, IconName>;

export interface IconTheme {
  iconDefinitions: Record<string, { iconPath: string }>;
  file: IconName;
  folder: IconName;
  folderExpanded: IconName;
  rootFolder: IconName;
  rootFolderExpanded: IconName;
  folderNames: IconMap;
  folderNamesExpanded: IconMap;
  fileExtensions: IconMap;
  fileNames: IconMap;
  hidesExplorerArrows: boolean;
}

const folderNames: IconMap = {
  ".github": "github",
  workflows: "github-actions",
  ".storybook": "storybook",
  k8s: "kubernetes",
};

export const iconTheme: IconTheme = {
  iconDefinitions: Object.fromEntries(
    Object.keys(glyphs).map((name) => [name, { iconPath: `./icons/${name}.svg` }]),
  ),
  file: "file",
  folder: "folder",
  folderExpanded: "folder-open",
  rootFolder: "folder",
  rootFolderExpanded: "folder-open",
  folderNames,
  folderNamesExpanded: folderNames,
  fileExtensions: {
    py: "python",
    pyw: "python",
    pyi: "python",
    ipynb: "jupyter",
    ts: "typescript",
    mts: "typescript",
    cts: "typescript",
    tsx: "react",
    js: "javascript",
    mjs: "javascript",
    cjs: "javascript",
    jsx: "react",
    "test.ts": "test",
    "spec.ts": "test",
    "test.tsx": "test",
    "test.js": "test",
    "spec.js": "test",
    rs: "rust",
    go: "go",
    php: "php",
    rb: "ruby",
    kt: "kotlin",
    kts: "kotlin",
    swift: "swift",
    dart: "dart",
    c: "c",
    h: "c",
    cpp: "cpp",
    cc: "cpp",
    cxx: "cpp",
    hpp: "cpp",
    lua: "lua",
    r: "r",
    rmd: "r",
    scala: "scala",
    ex: "elixir",
    exs: "elixir",
    hs: "haskell",
    zig: "zig",
    csproj: "dotnet",
    fsproj: "dotnet",
    sln: "dotnet",
    cs: "csharp",
    java: "java",
    jar: "java",
    ps1: "powershell",
    psm1: "powershell",
    psd1: "powershell",
    sh: "shell",
    bash: "shell",
    zsh: "shell",
    fish: "shell",
    html: "html",
    htm: "html",
    css: "css",
    scss: "sass",
    sass: "sass",
    less: "less",
    vue: "vue",
    svelte: "svelte",
    astro: "astro",
    tf: "terraform",
    tfvars: "terraform",
    json: "json",
    jsonc: "json",
    json5: "json",
    yml: "yaml",
    yaml: "yaml",
    toml: "toml",
    xml: "xml",
    md: "markdown",
    mdx: "markdown",
    graphql: "graphql",
    gql: "graphql",
    prisma: "prisma",
    sql: "postgresql",
    sqlite: "sqlite",
    db: "sqlite",
    env: "env",
    svg: "svg",
    png: "image",
    jpg: "image",
    jpeg: "image",
    gif: "image",
    webp: "image",
    avif: "image",
    ico: "image",
    lock: "lock",
    ini: "config",
    cfg: "config",
    conf: "config",
    properties: "config",
  },
  fileNames: {
    dockerfile: "docker",
    ".dockerignore": "docker",
    "compose.yml": "docker",
    "compose.yaml": "docker",
    "docker-compose.yml": "docker",
    "docker-compose.yaml": "docker",
    ".gitignore": "git",
    ".gitattributes": "git",
    ".gitmodules": "git",
    codeowners: "github",
    "package.json": "npm",
    "package-lock.json": "npm",
    ".npmrc": "npm",
    "pnpm-lock.yaml": "pnpm",
    "pnpm-workspace.yaml": "pnpm",
    "yarn.lock": "yarn",
    ".yarnrc.yml": "yarn",
    "bun.lock": "bun",
    "bun.lockb": "bun",
    "bunfig.toml": "bun",
    "deno.json": "deno",
    "deno.jsonc": "deno",
    ".node-version": "nodejs",
    ".nvmrc": "nodejs",
    "tsconfig.json": "typescript",
    "vite.config.ts": "vite",
    "vite.config.js": "vite",
    "vite.config.mts": "vite",
    "webpack.config.js": "webpack",
    "eslint.config.js": "eslint",
    "eslint.config.mjs": "eslint",
    ".eslintrc.json": "eslint",
    ".prettierrc": "prettier",
    "prettier.config.js": "prettier",
    "biome.json": "biome",
    "biome.jsonc": "biome",
    "vitest.config.ts": "vitest",
    "jest.config.js": "jest",
    "jest.config.ts": "jest",
    "tailwind.config.js": "tailwind",
    "tailwind.config.ts": "tailwind",
    "next.config.js": "nextjs",
    "next.config.mjs": "nextjs",
    "next.config.ts": "nextjs",
    "astro.config.mjs": "astro",
    "astro.config.ts": "astro",
    "svelte.config.js": "svelte",
    "angular.json": "angular",
    "manage.py": "django",
    "requirements.txt": "python",
    "pyproject.toml": "python",
    gemfile: "ruby",
    "gemfile.lock": "ruby",
    "config.ru": "rails",
    "cargo.toml": "rust",
    "cargo.lock": "rust",
    "go.mod": "go",
    "go.sum": "go",
    "composer.json": "php",
    artisan: "laravel",
    "application.properties": "spring",
    "application.yml": "spring",
    "kustomization.yaml": "kubernetes",
    "nginx.conf": "nginx",
    "redis.conf": "redis",
    "my.cnf": "mysql",
    "mongod.conf": "mongodb",
    ".env": "env",
    ".env.local": "env",
    ".env.example": "env",
    license: "license",
    licence: "license",
    "license.md": "license",
    ".editorconfig": "config",
    ".vscodeignore": "config",
  },
  hidesExplorerArrows: false,
};
