/* Colours for the VS Code interface around the code: bars, tabs, lists, widgets,
   gutter, diagnostics and the terminal. Keys are listed at
   https://code.visualstudio.com/api/references/theme-color */

import { withAlpha } from "../color.ts";
import { accent, ansi, brackets, signal, surface, syntax, text } from "../roles.ts";
import type { WorkbenchColors } from "./types.ts";

export const workbench: WorkbenchColors = {
  foreground: text.primary,
  descriptionForeground: text.muted,
  errorForeground: signal.error,
  focusBorder: accent.focus,
  "icon.foreground": text.secondary,
  "selection.background": surface.selection,
  "widget.shadow": surface.shadow,
  "sash.hoverBorder": accent.focus,
  "progressBar.background": accent.progress,
  "textLink.foreground": accent.link,
  "textLink.activeForeground": accent.linkActive,

  "titleBar.activeBackground": surface.bezel,
  "titleBar.activeForeground": text.primary,
  "titleBar.inactiveBackground": surface.bezel,
  "titleBar.inactiveForeground": text.muted,
  "titleBar.border": surface.border,

  "activityBar.background": surface.bezel,
  "activityBar.foreground": text.primary,
  "activityBar.inactiveForeground": text.muted,
  "activityBar.activeBorder": accent.primary,
  "activityBar.border": surface.border,
  "activityBarBadge.background": accent.badge,
  "activityBarBadge.foreground": text.onAccent,
  "badge.background": accent.badge,
  "badge.foreground": text.onAccent,

  "sideBar.background": surface.shade,
  "sideBar.foreground": text.secondary,
  "sideBar.border": surface.border,
  "sideBarTitle.foreground": text.primary,
  "sideBarSectionHeader.background": surface.shade,
  "sideBarSectionHeader.foreground": text.primary,
  "sideBarSectionHeader.border": surface.border,

  "list.activeSelectionBackground": surface.selection,
  "list.activeSelectionForeground": text.primary,
  "list.inactiveSelectionBackground": surface.inactiveSelection,
  "list.hoverBackground": surface.widget,
  "list.focusOutline": accent.focus,
  "list.highlightForeground": accent.primary,
  "list.errorForeground": signal.error,
  "list.warningForeground": signal.warning,

  "editorGroup.border": surface.border,
  "editorGroupHeader.tabsBackground": surface.shade,
  "editorGroupHeader.tabsBorder": surface.border,
  "tab.activeBackground": surface.editor,
  "tab.activeForeground": text.primary,
  "tab.activeBorderTop": accent.primary,
  "tab.unfocusedActiveBorderTop": withAlpha(accent.primary, 0.4),
  "tab.inactiveBackground": surface.shade,
  "tab.inactiveForeground": text.muted,
  "tab.hoverBackground": surface.widget,
  "tab.border": surface.bezel,
  "breadcrumb.foreground": text.muted,
  "breadcrumb.focusForeground": text.primary,
  "breadcrumb.activeSelectionForeground": accent.primary,

  "editor.background": surface.editor,
  "editor.foreground": syntax.variable,
  "editorCursor.foreground": accent.cursor,
  "editor.lineHighlightBackground": surface.lineHighlight,
  "editor.selectionBackground": surface.selection,
  "editor.inactiveSelectionBackground": surface.inactiveSelection,
  "editor.selectionHighlightBackground": surface.inactiveSelection,
  "editor.wordHighlightBackground": surface.wordHighlight,
  "editor.wordHighlightStrongBackground": surface.wordHighlightStrong,
  "editor.findMatchBackground": surface.findMatch,
  "editor.findMatchBorder": accent.cursor,
  "editor.findMatchHighlightBackground": surface.findMatchOther,
  "editorLineNumber.foreground": text.faint,
  "editorLineNumber.activeForeground": accent.primary,
  "editorIndentGuide.background1": surface.border,
  "editorIndentGuide.activeBackground1": text.faint,
  "editorWhitespace.foreground": surface.border,
  "editorRuler.foreground": surface.border,
  "editorBracketMatch.background": withAlpha(accent.primary, 0.12),
  "editorBracketMatch.border": withAlpha(accent.primary, 0.5),
  "editorBracketHighlight.foreground1": brackets.first,
  "editorBracketHighlight.foreground2": brackets.second,
  "editorBracketHighlight.foreground3": brackets.third,
  "editorBracketHighlight.foreground4": brackets.first,
  "editorBracketHighlight.foreground5": brackets.second,
  "editorBracketHighlight.foreground6": brackets.third,
  "editorBracketHighlight.unexpectedBracket.foreground": signal.error,

  "editorError.foreground": signal.error,
  "editorWarning.foreground": signal.warning,
  "editorInfo.foreground": signal.info,
  "editorHint.foreground": signal.hint,
  "editorGutter.addedBackground": signal.added,
  "editorGutter.modifiedBackground": signal.modified,
  "editorGutter.deletedBackground": signal.deleted,
  "editorOverviewRuler.border": surface.border,
  "editorOverviewRuler.errorForeground": signal.error,
  "editorOverviewRuler.warningForeground": signal.warning,
  "editorOverviewRuler.infoForeground": signal.info,
  "editorOverviewRuler.findMatchForeground": accent.cursor,
  "diffEditor.insertedTextBackground": withAlpha(signal.added, 0.14),
  "diffEditor.removedTextBackground": withAlpha(signal.deleted, 0.14),

  "editorWidget.background": surface.widget,
  "editorWidget.border": surface.border,
  "editorHoverWidget.background": surface.widget,
  "editorHoverWidget.border": surface.border,
  "editorSuggestWidget.background": surface.widget,
  "editorSuggestWidget.border": surface.border,
  "editorSuggestWidget.selectedBackground": surface.selection,
  "editorSuggestWidget.highlightForeground": accent.primary,
  "peekView.border": accent.primary,
  "peekViewTitle.background": surface.widget,
  "peekViewEditor.background": surface.shade,
  "peekViewResult.background": surface.bezel,

  "scrollbar.shadow": surface.shadow,
  "scrollbarSlider.background": withAlpha(text.primary, 0.12),
  "scrollbarSlider.hoverBackground": withAlpha(text.primary, 0.2),
  "scrollbarSlider.activeBackground": withAlpha(text.primary, 0.3),

  "input.background": surface.shade,
  "input.foreground": text.primary,
  "input.border": text.faint,
  "input.placeholderForeground": text.muted,
  "inputOption.activeBorder": accent.primary,
  "inputValidation.errorBorder": signal.error,
  "inputValidation.warningBorder": signal.warning,
  "inputValidation.infoBorder": signal.info,
  "dropdown.background": surface.widget,
  "dropdown.border": text.faint,
  "button.background": accent.primary,
  "button.foreground": text.onAccent,
  "button.hoverBackground": accent.hover,
  "button.secondaryBackground": surface.widget,
  "button.secondaryForeground": text.primary,

  "panel.background": surface.shade,
  "panel.border": surface.border,
  "panelTitle.activeBorder": accent.primary,
  "panelTitle.activeForeground": text.primary,
  "panelTitle.inactiveForeground": text.muted,

  "statusBar.background": surface.bezel,
  "statusBar.foreground": text.secondary,
  "statusBar.border": surface.border,
  "statusBar.noFolderBackground": surface.bezel,
  "statusBar.debuggingBackground": signal.error,
  "statusBar.debuggingForeground": text.onAccent,
  "statusBarItem.hoverBackground": surface.widget,
  "statusBarItem.remoteBackground": accent.badge,
  "statusBarItem.remoteForeground": text.onAccent,

  "notifications.background": surface.widget,
  "notifications.border": surface.border,
  "notificationsErrorIcon.foreground": signal.error,
  "notificationsWarningIcon.foreground": signal.warning,
  "notificationsInfoIcon.foreground": signal.info,

  "gitDecoration.addedResourceForeground": signal.added,
  "gitDecoration.untrackedResourceForeground": signal.added,
  "gitDecoration.modifiedResourceForeground": signal.modified,
  "gitDecoration.deletedResourceForeground": signal.deleted,
  "gitDecoration.conflictingResourceForeground": signal.conflict,
  "gitDecoration.ignoredResourceForeground": signal.ignored,

  "terminal.background": surface.shade,
  "terminal.foreground": text.primary,
  "terminalCursor.foreground": accent.cursor,
  "terminal.ansiBlack": ansi.black,
  "terminal.ansiRed": ansi.red,
  "terminal.ansiGreen": ansi.green,
  "terminal.ansiYellow": ansi.yellow,
  "terminal.ansiBlue": ansi.blue,
  "terminal.ansiMagenta": ansi.magenta,
  "terminal.ansiCyan": ansi.cyan,
  "terminal.ansiWhite": ansi.white,
  "terminal.ansiBrightBlack": ansi.brightBlack,
  "terminal.ansiBrightRed": ansi.brightRed,
  "terminal.ansiBrightGreen": ansi.brightGreen,
  "terminal.ansiBrightYellow": ansi.brightYellow,
  "terminal.ansiBrightBlue": ansi.brightBlue,
  "terminal.ansiBrightMagenta": ansi.brightMagenta,
  "terminal.ansiBrightCyan": ansi.brightCyan,
  "terminal.ansiBrightWhite": ansi.brightWhite,
};
