/* Colours for the VS Code interface around the code: bars, tabs, lists, widgets,
   gutter, diagnostics and the terminal. Keys are listed at
   https://code.visualstudio.com/api/references/theme-color */

import { accent, ansi, brackets, signal, surface, syntax, text } from "../roles.ts";
import type { WorkbenchColors } from "./types.ts";

export const workbench: WorkbenchColors = {
  foreground: text.primary,
  descriptionForeground: text.muted,
  errorForeground: signal.error,
  focusBorder: accent.focus,
  "icon.foreground": text.secondary,
  "selection.background": surface.selection,
  "widget.shadow": surface.shadow,
  "widget.border": surface.vividEdge,
  "sash.hoverBorder": accent.vivid,
  "progressBar.background": accent.progress,
  "textLink.foreground": accent.link,
  "textLink.activeForeground": accent.linkActive,

  "titleBar.activeBackground": surface.frame,
  "titleBar.activeForeground": accent.primary,
  "titleBar.inactiveBackground": surface.frame,
  "titleBar.inactiveForeground": text.muted,
  "titleBar.border": surface.vividEdge,

  "activityBar.background": surface.frame,
  "activityBar.foreground": accent.highlight,
  "activityBar.inactiveForeground": text.muted,
  "activityBar.activeBorder": accent.vivid,
  "activityBar.activeBackground": surface.hover,
  "activityBar.border": surface.border,
  "activityBarBadge.background": accent.badge,
  "activityBarBadge.foreground": text.onAccent,
  "badge.background": accent.badge,
  "badge.foreground": text.onAccent,

  "sideBar.background": surface.shade,
  "sideBar.foreground": text.secondary,
  "sideBar.border": surface.border,
  "sideBarTitle.foreground": accent.primary,
  "sideBarSectionHeader.background": surface.frame,
  "sideBarSectionHeader.foreground": accent.primary,
  "sideBarSectionHeader.border": surface.border,

  "list.activeSelectionBackground": surface.selection,
  "list.activeSelectionForeground": accent.highlight,
  "list.inactiveSelectionBackground": surface.inactiveSelection,
  "list.hoverBackground": surface.hover,
  "list.focusOutline": accent.focus,
  "list.highlightForeground": accent.highlight,
  "list.errorForeground": signal.error,
  "list.warningForeground": signal.warning,
  "tree.indentGuidesStroke": surface.border,
  "pickerGroup.foreground": accent.primary,
  "quickInputList.focusBackground": surface.selection,
  "menu.background": surface.widget,
  "menu.selectionBackground": surface.selection,
  "menu.selectionForeground": accent.highlight,

  "editorGroup.border": surface.border,
  "editorGroupHeader.tabsBackground": surface.frame,
  "editorGroupHeader.tabsBorder": surface.border,
  "tab.activeBackground": surface.editor,
  "tab.activeForeground": accent.primary,
  "tab.activeBorderTop": accent.vivid,
  "tab.activeModifiedBorder": accent.highlight,
  "tab.unfocusedActiveBorderTop": surface.vividEdge,
  "tab.inactiveBackground": surface.frame,
  "tab.inactiveForeground": text.muted,
  "tab.hoverBackground": surface.hover,
  "tab.border": surface.frame,
  "breadcrumb.foreground": text.muted,
  "breadcrumb.focusForeground": text.primary,
  "breadcrumb.activeSelectionForeground": accent.highlight,

  "editor.background": surface.editor,
  "editor.foreground": syntax.variable,
  "editorCursor.foreground": accent.cursor,
  "editor.lineHighlightBackground": surface.lineHighlight,
  "editor.lineHighlightBorder": surface.lineHighlightBorder,
  "editor.selectionBackground": surface.selection,
  "editor.inactiveSelectionBackground": surface.inactiveSelection,
  "editor.selectionHighlightBackground": surface.inactiveSelection,
  "editor.wordHighlightBackground": surface.wordHighlight,
  "editor.wordHighlightStrongBackground": surface.wordHighlightStrong,
  "editor.findMatchBackground": surface.findMatch,
  "editor.findMatchBorder": accent.cursor,
  "editor.findMatchHighlightBackground": surface.findMatchOther,
  "editorLineNumber.foreground": text.faint,
  "editorLineNumber.activeForeground": accent.highlight,
  "editorIndentGuide.background1": surface.border,
  "editorIndentGuide.activeBackground1": surface.activeGuide,
  "editorWhitespace.foreground": surface.border,
  "editorRuler.foreground": surface.border,
  "editorBracketMatch.background": surface.hover,
  "editorBracketMatch.border": accent.highlight,
  "editorBracketHighlight.foreground1": brackets.first,
  "editorBracketHighlight.foreground2": brackets.second,
  "editorBracketHighlight.foreground3": brackets.third,
  "editorBracketHighlight.foreground4": brackets.first,
  "editorBracketHighlight.foreground5": brackets.second,
  "editorBracketHighlight.foreground6": brackets.third,
  "editorBracketHighlight.unexpectedBracket.foreground": signal.error,

  "editorError.foreground": signal.error,
  "editorWarning.foreground": signal.warning,
  "editorInfo.foreground": signal.info,
  "editorHint.foreground": signal.hint,
  "editorGutter.addedBackground": signal.added,
  "editorGutter.modifiedBackground": signal.modified,
  "editorGutter.deletedBackground": signal.deleted,
  "editorOverviewRuler.border": surface.border,
  "editorOverviewRuler.errorForeground": signal.error,
  "editorOverviewRuler.warningForeground": signal.warning,
  "editorOverviewRuler.infoForeground": signal.info,
  "editorOverviewRuler.findMatchForeground": accent.cursor,
  "minimap.findMatchHighlight": accent.cursor,
  "minimap.selectionHighlight": surface.selection,
  "diffEditor.insertedTextBackground": surface.inactiveSelection,
  "diffEditor.removedTextBackground": surface.wordHighlightStrong,

  "editorWidget.background": surface.widget,
  "editorWidget.border": surface.vividEdge,
  "editorHoverWidget.background": surface.widget,
  "editorHoverWidget.border": surface.vividEdge,
  "editorSuggestWidget.background": surface.widget,
  "editorSuggestWidget.border": surface.vividEdge,
  "editorSuggestWidget.selectedBackground": surface.selection,
  "editorSuggestWidget.highlightForeground": accent.highlight,
  "peekView.border": accent.vivid,
  "peekViewTitle.background": surface.banner,
  "peekViewTitleLabel.foreground": accent.primary,
  "peekViewEditor.background": surface.shade,
  "peekViewResult.background": surface.frame,

  "scrollbar.shadow": surface.shadow,
  "scrollbarSlider.background": surface.inactiveSelection,
  "scrollbarSlider.hoverBackground": surface.selection,
  "scrollbarSlider.activeBackground": surface.vividEdge,

  "input.background": surface.frame,
  "input.foreground": text.primary,
  "input.border": text.faint,
  "input.placeholderForeground": text.muted,
  "inputOption.activeBorder": accent.highlight,
  "inputValidation.errorBorder": signal.error,
  "inputValidation.warningBorder": signal.warning,
  "inputValidation.infoBorder": signal.info,
  "dropdown.background": surface.widget,
  "dropdown.border": text.faint,
  "button.background": accent.primary,
  "button.foreground": text.onAccent,
  "button.hoverBackground": accent.hover,
  "button.secondaryBackground": surface.banner,
  "button.secondaryForeground": accent.primary,

  "panel.background": surface.shade,
  "panel.border": surface.vividEdge,
  "panelTitle.activeBorder": accent.focus,
  "panelTitle.activeForeground": accent.primary,
  "panelTitle.inactiveForeground": text.muted,

  "statusBar.background": surface.banner,
  "statusBar.foreground": accent.primary,
  "statusBar.border": accent.vivid,
  "statusBar.noFolderBackground": surface.banner,
  "statusBar.debuggingBackground": signal.error,
  "statusBar.debuggingForeground": text.onAccent,
  "statusBarItem.hoverBackground": surface.hover,
  "statusBarItem.remoteBackground": accent.vivid,
  "statusBarItem.remoteForeground": text.onAccent,

  "notifications.background": surface.widget,
  "notifications.border": surface.vividEdge,
  "notificationCenterHeader.background": surface.banner,
  "notificationsErrorIcon.foreground": signal.error,
  "notificationsWarningIcon.foreground": signal.warning,
  "notificationsInfoIcon.foreground": signal.info,

  "gitDecoration.addedResourceForeground": signal.added,
  "gitDecoration.untrackedResourceForeground": signal.added,
  "gitDecoration.modifiedResourceForeground": signal.modified,
  "gitDecoration.deletedResourceForeground": signal.deleted,
  "gitDecoration.conflictingResourceForeground": signal.conflict,
  "gitDecoration.ignoredResourceForeground": signal.ignored,

  "terminal.background": surface.terminal,
  "terminal.foreground": text.terminal,
  "terminalCursor.foreground": accent.cursor,
  "terminal.ansiBlack": ansi.black,
  "terminal.ansiRed": ansi.red,
  "terminal.ansiGreen": ansi.green,
  "terminal.ansiYellow": ansi.yellow,
  "terminal.ansiBlue": ansi.blue,
  "terminal.ansiMagenta": ansi.magenta,
  "terminal.ansiCyan": ansi.cyan,
  "terminal.ansiWhite": ansi.white,
  "terminal.ansiBrightBlack": ansi.brightBlack,
  "terminal.ansiBrightRed": ansi.brightRed,
  "terminal.ansiBrightGreen": ansi.brightGreen,
  "terminal.ansiBrightYellow": ansi.brightYellow,
  "terminal.ansiBrightBlue": ansi.brightBlue,
  "terminal.ansiBrightMagenta": ansi.brightMagenta,
  "terminal.ansiBrightCyan": ansi.brightCyan,
  "terminal.ansiBrightWhite": ansi.brightWhite,
};
